language: php
matrix:
  include:
  - os: linux
    compiler: gcc
    sudo: required
    dist: bionic
install:
- export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- travis_retry sudo apt-get install software-properties-common
- travis_retry sudo add-apt-repository -y ppa:ondrej/php
- travis_retry sudo apt-get update
- travis_retry sudo apt install -y php7.4 php7.4-dev php7.4-cli
  php7.4-mbstring php7.4-curl php7.4-xml php7.4-intl
- curl -sS https://getcomposer.org/installer -o composer-setup.php
- sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
before_script:
- sh $TRAVIS_BUILD_DIR/_extensions/setup.sh -all
- composer install
script: vendor/bin/phpunit --configuration phpunit.xml
